spring.application.name=uniday

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/uniteq?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=uniteq
spring.datasource.password=uniteq

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Codificación
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
